### ISSUE TITLE
"Define and operate on a type represented as a bitfield" recipe

### ISSUE THREAD

**Issue by brson** [brson/rust-cookbook#189] opened 2017-06-07 00:44 UTC
Use the bitflags crate.

**Comment by brson** [comment] 2017-06-07 00:46
Maybe show the creation of the type and a few representative operators and method calls, just to give a taste of what's possible.

**Comment by budziq** [comment] 2017-06-23 17:12
duplicate of https://github.com/brson/rust-cookbook/issues/114

**Closed by budziq** 2017-06-23 17:12 UTC
Labels: easy, example, wip
